# Generated by Django 5.0.2 on 2024-03-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog_slug_hostel_slug_seo_name_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='myapp.amenity'),
        ),
        migrations.AlterField(
            model_name='images',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.hostel'),
        ),
    ]
