# Generated by Django 5.0.2 on 2024-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_hostel_amenities_alter_images_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='bath',
            field=models.CharField(default='Atachedt/Common', max_length=255),
        ),
        migrations.AddField(
            model_name='hostel',
            name='bed',
            field=models.CharField(default='Single/Double/Triple', max_length=255),
        ),
        migrations.AddField(
            model_name='hostel',
            name='cafeteria',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostelType',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=50),
        ),
    ]
