# Generated by Django 5.0.2 on 2024-04-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hostel_address_hostel_details_hostel_nearby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='bath',
            field=models.TextField(default='Atachedt/Common', max_length=255),
        ),
    ]
