# Generated by Django 5.0.2 on 2024-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_hostel_bath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='details',
            field=models.TextField(default='', max_length=2055),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='nearby',
            field=models.TextField(default='Sharda University : 0.2km', max_length=550),
        ),
    ]
