# Generated by Django 5.0.2 on 2024-04-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_hostel_details_alter_hostel_nearby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='cafeteria',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes'),
        ),
    ]
