# Generated by Django 5.0.2 on 2024-04-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_hostel_google_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='google_map_location',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
