# Generated by Django 5.0.2 on 2024-04-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_hostel_google_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hostel_videos/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_video_thumbnails/'),
        ),
    ]
