# Generated by Django 5.0.2 on 2024-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_hostel_video_hostel_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='student_addr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
