# Generated by Django 5.0.2 on 2024-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_testimonial_student_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
