# Generated by Django 5.0.2 on 2024-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_blogtag_remove_blog_tags_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
