# Generated by Django 5.0.2 on 2024-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_blog_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(max_length=550),
        ),
    ]
