# Generated by Django 5.0.2 on 2024-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_seo_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='bed',
        ),
        migrations.AddField(
            model_name='hostel',
            name='beds',
            field=models.ManyToManyField(blank=True, to='myapp.bedtype'),
        ),
    ]
