# Generated by Django 5.0.2 on 2024-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_bedtype_remove_hostel_bed_hostel_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Attached', 'Attached'), ('Common', 'Common')], max_length=50, unique=True)),
            ],
        ),
    ]
