# Generated by Django 5.0.2 on 2024-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_bathtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='bath',
        ),
        migrations.AddField(
            model_name='hostel',
            name='bath',
            field=models.ManyToManyField(blank=True, to='myapp.bathtype'),
        ),
    ]
