# Generated by Django 5.0.2 on 2024-04-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_hostel_bath_hostel_bath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='myapp.city'),
        ),
    ]
