# Generated by Django 5.0.2 on 2024-04-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_hostel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtype',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Tripple', 'Tripple')], max_length=50, unique=True),
        ),
    ]
