# Generated by Django 5.0.2 on 2024-04-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_bedtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
