# Generated by Django 5.0.2 on 2024-04-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], default='Publish', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='media/blogs/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/hostels/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/hostel_videos/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/hostel_video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/hostel_images/img'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='media/testimonials/'),
        ),
    ]
