# Generated by Django 5.0.2 on 2024-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_sentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft'), ('Seo', 'Seo')], default='Seo', max_length=50),
        ),
    ]
