# Generated by Django 5.0.2 on 2024-05-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog', to='myapp.seo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='myapp.blogtag'),
        ),
    ]
