# Generated by Django 5.0.2 on 2024-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_blog_seo_alter_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
