# Generated by Django 5.0.2 on 2024-06-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtype',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Four', 'Four')], max_length=50, unique=True),
        ),
    ]
